<?php

namespace Sales\DemandeBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * demandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class demandeRepository extends EntityRepository
{
}
